config/routes.rb
RailsCrudGroup::Application.routes.draw do

root 'profiles#index'
resources :categories
resources :profiles

match 'auth/:provider/callback', to:'sessions#create', via: [:get, :post]
match 'auth/failure', to: redirect('/'), via: [:get, :post]
match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  

end

app/models/category.rb
class Category < ActiveRecord::Base

	has_many :profiles

	validates_presence_of :name

end

app/models/profile.rb
class Profile < ActiveRecord::Base

	belongs_to :category
	mount_uploader :photo, PhotoUploader
end

app/models/user.rb
class User < ActiveRecord::Base

	def self.from_omniauth(auth)
		where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
			user.provider = auth.provider
			user.uid = auth.uid
			user.name = auth.info.name
			user.oauth_token = auth.credentials.token
			user.oauth_expires_at = Time.at(auth.credentials.expires_at)
			user.save!
		end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  layout 'yeti'

  private
  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	#將重複的函式使用 before_filter法 來省略掉

	before_action :find_category, :only =>[:show, :edit, :update, :destroy]

	def index
		#@categories = Category.all  因為使用了分頁外掛 kaminari，所以註解掉了
		@categories = Category.page(params[:page]).per(5)

		  respond_to do |format|
		    format.html # index.html.erb
		    format.xml { render :xml => @categories.to_xml }
		    format.json { render :json => @categories.to_json }
		    format.atom { @feed_title = "正心特學特約商店清單" } # index.atom.builder
		  end
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)
		
		if @category.save
			redirect_to categories_path
		else
			render :action => :new
		end

		flash[:notice] = "行業別已經成功被建立"
	end

	def show
		@page_title = @category.name
	end

	def edit
	end

	def update
		if @category.update_attributes(category_params)
			redirect_to category_path(@category)
		else
			render :action => :edit
		end

		flash[:notice] = "行業別已經成功被更新"
	end

	def destroy
		@category.destroy

		redirect_to categories_path

		flash[:alert] = "行業別已經成功被刪除"
	end

	protected  
	
	# rails 4.0 之後才有的安全設定，要宣告允許使用的變數
	# 所以將 params[:category]以『category_params』替代
	def category_params
		params.require(:category).permit(:name,:description)
	end 

	#配合上面before_filter 來省略重複的事情
	def find_category
		@category = Category.find(params[:id])
	end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

#將重複的函式使用 before_filter法 來省略掉

	before_action :find_profile, :only =>[:show, :edit, :update, :destroy]

	def index
		@profiles = Profile.all  
		 #@profiles = profile.page(params[:page]).per(5)

		 #因為使用了分頁外掛 kaminari，所以註解掉了

		  #respond_to do |format|
		   # format.html # index.html.erb
		    #format.xml { render :xml => @profiles.to_xml }
		    #format.json { render :json => @profiles.to_json }
		    #format.atom { @feed_title = "正心中學特約商店清單" } # index.atom.builder
		  #end
	end

	def new
		@profile = Profile.new
	end

	def create
		@profile = Profile.new(profile_params)
		
		if @profile.save
			redirect_to profiles_path
		else
			render :action => :new
		end

		flash[:notice] = "特約清單已經成功被建立"
	end

	def show
	end

	def edit
	end

	def update
		if @profile.update_attributes(profile_params)
			redirect_to profile_path(@profile)
		else
			render :action => :edit
		end

		flash[:notice] = "特約清單已經成功被更新"
	end

	def destroy
		@profile.destroy

		redirect_to profiles_path

		flash[:alert] = "特約清單已經成功被刪除"
	end

	protected  
	
	# rails 4.0 之後才有的安全設定，要宣告允許使用的變數
	# 所以將 params[:profile]以『profile_params』替代
	def profile_params
		params.require(:profile).permit(:title,:category_id,:phone,:fax,:address,:boss,:description,:pledge,:map,:photo,:promotions,:datetime,:link,:reference,:recommendation,:note)
	end 

	#配合上面before_action 來省略重複的事情
	def find_profile
		@profile = Profile.find(params[:id])
	end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def create
		user = User.from_omniauth(env["omniauth.auth"])
		session[:user_id] = user.id
		redirect_to root_url
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_url
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/categories/_form.html.erb
<%= form_for @category, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                categories_path, :class => 'btn' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/categories/index.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1>商店類別</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>編號</th>
      <th>類別名稱</th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to category.id, category_path(category) %></td>
        <td><%= category.name %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_category_path(category), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      category_path(category),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => '你確定嗎?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_category_path,
            :class => 'btn btn-primary' %>

app/views/categories/new.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/categories/show.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @category.name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              categories_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_category_path(@category), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              category_path(@category),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> <%= @page_title || "正心中學特約商店" %> </title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<p style="color: green"><%= flash[:notice] %></p>
	<p style="color: red"><%= flash[:alert] %></p>
	<%= yield %>

</body>
</html>

app/views/layouts/cerulean.html.erb
<!DOCTYPE html>
<html lang="zn-TW">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "rails_crud_group" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "cerulean", :media => "all" %>

    <%= yield(:page_stylesheet) if content_for?(:page_stylesheet) %>

  </head>
  <body>

    <!-- Fixed navbar -->
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">正心高級中學特約商店</a>
        </div>
        <div class="navbar-collapse collapse pull-right">
          <ul class="nav navbar-nav">
            <li><a href='/'>首頁</a></li>
            <li><a href="/profiles">特約商店</a></li>
            <li><a href="/categories">新增類別</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">會員管理<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#"></a></li>
                <li><a href="#">加入會員</a></li>
                <li><a href="#">登入</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">oAuth 2.0</li>
                <li>
                  <div id="user-widget">
                    <% if current_user %>
                      Welcome <strong><%= current_user.name %></strong>!
                      <%= link_to "Sign out", signout_path, id: "sign_out" %>
                    <% else %>
                      <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
                      <%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %>
                    <% end %>
                  </div>
                  </li>
              </ul>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>


    <div class="container">
     
      <%= yield %>

        <footer class="footer">
          <small>
            © Copyright, 2013 <a href="http://www.shsh.ylc.edu.tw">正心高級中學</a> All Rights Reserved.
          </small>  

          <nav>
            <ul>
              <li><a href='http://www.shsh.ylc.edu.tw'>正心高級中學</a></li>
              <li><a href="http://student.coolsea.net">大魏老師的資訊課程</a></li>
            </ul>
          </nav>
        </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "cerulean" %>
    <%= yield(:page_javascript) if content_for?(:page_javascript) %>
  </body>
</html>

app/views/profiles/_form.html.erb
<%= form_for @profile, :html => { :class => 'form-horizontal',:multipart => true } do |f| %>


    <!-- Forms
      ================================================== -->
      <div class="bs-docs-section">

        <div class="row">
          <div class="col-lg-6">
            <div class="well">
              <form class="bs-example form-horizontal">
                <fieldset>
                  <legend>基本資料</legend>
                  
                  <div class="form-group">
                    <label for="inputTitle" class="col-lg-2 control-label">商店名稱</label>
                    <div class="col-lg-10">
                      <%= f.text_field :title, :class => 'text_field, form-control',placeholder: "店名" %>
                    </div>
                  </div>

                  <div class="form-group">
                    <label for="inputCategory" class="col-lg-2 control-label">商店類別</label>
                    <div class="col-lg-10">
                      <%= f.select :category_id, Category.all.map{ |c| [c.name, c.id] } , :class => 'form-control'%>
                    </div>
                  </div>
                  
                  <div class="form-group">
                    <label for="inputPhone" class="col-lg-2 control-label">電話</label>
                    <div class="col-lg-10">
                      <%= f.number_field :phone, :class => 'number_field, form-control',placeholder: "電話" %>
                    </div>
                  </div>

                  <div class="form-group">
                    <label for="inputFax" class="col-lg-2 control-label">傳真</label>
                    <div class="col-lg-10">
                      <%= f.number_field :fax, :class => 'number_field, form-control',placeholder: "傳真" %>
                    </div>
                  </div>

                  <div class="form-group">
                    <label for="inputaAddress" class="col-lg-2 control-label">地址</label>
                    <div class="col-lg-10">
                      <%= f.text_field :address, :class => 'text_field, form-control',placeholder: "地址"%>
                    </div>
                  </div>

                  <div class="form-group">
                    <label for="inputaBoss" class="col-lg-2 control-label">負責人</label>
                    <div class="col-lg-10">
                      <%= f.text_field :boss, :class => 'text_field, form-control',placeholder: "負責人"%>
                    </div>
                  </div>

                  <div class="form-group">
                    <label for="textArea" class="col-lg-2 control-label">簡介</label>
                    <div class="col-lg-10">
                      <%= f.text_area :description, :class => 'text_area, form-control',:row => '3' %>
                      <span class="help-block">您可以在此簡短的介紹這家店的特色與優惠。</span>
                    </div>
                  </div>

                  <div class="form-group">
                    <label for="textPledge" class="col-lg-2 control-label">優質堅持</label>
                    <div class="col-lg-10">
                      <%= f.text_area :pledge, :class => 'text_area, form-control',:row => '3' %>
                      <span class="help-block">店家的優質堅持宣言。</span>
                    </div>
                  </div>

                  <div class="form-group">
                    <label for="textMap" class="col-lg-2 control-label">地圖</label>
                    <div class="col-lg-10">
                      <%= f.text_area :map, :class => 'text_area, form-control',:row => '3' %>
                    </div>
                  </div>

                  <div class="form-group">
                    <label for="textPhoto" class="col-lg-2 control-label">簡介圖片</label>
                    <div class="col-lg-10">
                      <%= f.file_field :photo, :class => 'text_field' %>
                    </div>
                  </div>

                  <div class="form-group">
                    <label for="inputDatetime" class="col-lg-2 control-label">營業時間</label>
                    <div class="col-lg-10">
                      <%= f.datetime_select :datetime, :class => 'datetime, form-control'%>
                    </div>
                  </div>


                  <div class="form-group">
                    <label for="textPromotions" class="col-lg-2 control-label">優惠項目</label>
                    <div class="col-lg-10">
                      <%= f.text_area :promotions, :class => 'text_area, form-control',:row => '3' %>
                    </div>
                  </div>

                  <div class="form-group">
                    <label for="inputLink" class="col-lg-2 control-label">相關連結</label>
                    <div class="col-lg-10">
                      <%= f.text_field :link, :class => 'text_field, form-control'%>
                    </div>
                  </div>

                  <div class="form-group">
                    <label for="inputReference" class="col-lg-2 control-label">推薦人</label>
                    <div class="col-lg-10">
                      <%= f.text_field :reference, :class => 'text_field, form-control',placeholder: "（僅供委員會參考，將不顯示於網頁上）"%>
                    </div>
                  </div>

                  <div class="form-group">
                    <label for="textRecommendation" class="col-lg-2 control-label">推薦留言</label>
                    <div class="col-lg-10">
                      <%= f.text_area :recommendation, :class => 'text_area, form-control',:row => '3' %>
                    </div>
                  </div>

                  <div class="form-group">
                    <label for="textNote" class="col-lg-2 control-label">備註</label>
                    <div class="col-lg-10">
                      <%= f.text_area :note, :class => 'text_area, form-control',:row => '3' %>
                    </div>
                  </div>

                    <div class="form-actions, pull-right">
                      <%= f.submit '送出', :class => 'btn btn-primary' %>
                      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                                  profiles_path, :class => 'btn' %>
                    </div>

                </fieldset>
              </form>
            </div>
          </div>
        </div>
        
      </div>

    <% end %>

app/views/profiles/edit.html.erb
<%- model_class = Profile -%>
<div class="page-header">
  <h1>編輯商店</h1>
</div>
<%= render :partial => 'form' %>

app/views/profiles/index.html.erb
<%- model_class = Profile -%>
<div class="page-header">
  <h1>特約商店</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>編號</th>
      <th>商店名稱</th>
      <th>商店類別</th>
      <th>電話</th>
      <th>地址</th>
      <th>營業時間</th>
    </tr>
  </thead>
  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= link_to profile.id, profile_path(profile) %></td>
        <td><%= link_to profile.title, profile_path(profile) %></td>
        <td><%= profile.category.name %></td>
        <td><%= profile.phone %></td>
        <td><%= profile.address %></td>
        <td><%= profile.datetime %></td>
        <td>
          <%= link_to '編輯',edit_profile_path(profile), :class => 'btn btn-mini' %>
          <%= link_to '刪除' ,profile_path(profile),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => '你確定嗎?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_profile_path,
            :class => 'btn btn-primary' %>


    

app/views/profiles/new.html.erb
<%- model_class = Profile -%>
<div class="page-header">
  <h1>特約商店推薦表單</h1>
</div>
<%= render :partial => 'form' %>

app/views/profiles/show.html.erb
<%- model_class = Profile -%>
<div class="page-header">
  <h1>商店基本資料</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @profile.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:category_id) %>:</strong></dt>
  <dd>  <%= @profile.category.name %></dd>


  <dt><strong><%= model_class.human_attribute_name(:phone) %>:</strong></dt>
  <dd><%= @profile.phone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:fax) %>:</strong></dt>
  <dd><%= @profile.fax %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @profile.address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:boss) %>:</strong></dt>
  <dd><%= @profile.boss %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @profile.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:pledge) %>:</strong></dt>
  <dd><%= @profile.pledge %></dd>
  <dt><strong><%= model_class.human_attribute_name(:map) %>:</strong></dt>
  <dd><%= @profile.map %></dd>
  <dt><strong><%= model_class.human_attribute_name(:photo) %>:</strong></dt>
  <dd><%= image_tag(@profile.photo_url, :width => 300) if @profile.photo.present? %></dd>

  <dt><strong><%= model_class.human_attribute_name(:promotions) %>:</strong></dt>
  <dd><%= @profile.promotions %></dd>
  <dt><strong><%= model_class.human_attribute_name(:datetime) %>:</strong></dt>
  <dd><%= @profile.datetime %></dd>
  <dt><strong><%= model_class.human_attribute_name(:link) %>:</strong></dt>
  <dd><%= @profile.link %></dd>
  <dt><strong><%= model_class.human_attribute_name(:reference) %>:</strong></dt>
  <dd><%= @profile.reference %></dd>
  <dt><strong><%= model_class.human_attribute_name(:recommendation) %>:</strong></dt>
  <dd><%= @profile.recommendation %></dd>
  <dt><strong><%= model_class.human_attribute_name(:note) %>:</strong></dt>
  <dd><%= @profile.note %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              profiles_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_profile_path(@profile), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              profile_path(@profile),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>